[package]
name = "im-select-rs"
version = "0.1.0"
edition = "2024"

[profile.release]
lto = true
debug = false
strip = true
panic = "abort"
opt-level = "z"


[dependencies]
winapi = { version = "0.3", features = ["winuser"] }

