on:
  push:
    tags:
      - 'v*' 

env:
  CARGO_INCREMENTAL: 0

jobs:
  release:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - run: rustup update
      - run: cargo build --release

      - name: Create GitHub Release and upload exe
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/im-select-rs.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
